spring:
  application:
    name:beastxfit
  datasource:
            url: jdbc:postgresql://localhost:5432/fittnes-micro-user
            username: postgres
            password: beast123
            jpa:
              hibernate:
                ddl-auto: update
              database-platform: org.hibernate.dialect.PostgreSQLDialect
